services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['kernel.root_dir%/.credentials/calendar.json']]
            - [setClientSecret, ['%env(GOOGLE_CLIENT_SECRET)%']]
